'use server';
import { revalidatePath } from 'next/cache';
import { getViewer, isAdmin, isSuperAdmin } from '../../../lib/auth';
import { createServerSupabaseClient, isDemoMode } from '../../../lib/supabaseServerClient';
export async function manageContent(type,id,action,changes={}){const viewer=await getViewer();if(!isAdmin(viewer))return{ok:false,error:'Administrator access required'};if(isDemoMode){revalidatePath('/admin/content');return{ok:true,demo:true};}const supabase=await createServerSupabaseClient();const rpc=type==='announcement'&&action==='edit'?'manage_announcement_editorial':'manage_published_content';const args=rpc==='manage_announcement_editorial'?{p_announcement_id:id,p_action:'edit',p_priority:changes.priority||null,p_is_featured:changes.is_featured??null,p_featured_until:changes.featured_until||null,p_expires_at:changes.expires_at||null,p_category:changes.category||null,p_source_url:changes.source_url||null}:{p_content_type:type,p_content_id:id,p_action:action,p_changes:changes};const{data,error}=await supabase.rpc(rpc,args);if(error)return{ok:false,error:error.message};['/admin/content','/','/opportunities','/events','/events/all','/announcements'].forEach(revalidatePath);return{ok:true,data};}

export async function setHomeSpotlight(type,id,isFeatured,rank=99){const viewer=await getViewer();if(!isAdmin(viewer))return{ok:false,error:'Administrator access required'};if(isDemoMode){revalidatePath('/admin/content');revalidatePath('/');return{ok:true,demo:true};}const supabase=await createServerSupabaseClient();const{data,error}=await supabase.rpc('manage_home_spotlight',{p_content_type:type,p_content_id:id,p_is_featured:Boolean(isFeatured),p_rank:isFeatured?Math.max(1,Math.min(99,Number(rank)||99)):null});if(error)return{ok:false,error:error.message};revalidatePath('/admin/content');revalidatePath('/');return{ok:true,data};}

export async function setHomeEvent(id,visible,rank=99){const viewer=await getViewer();if(!isAdmin(viewer))return{ok:false,error:'Administrator access required'};if(isDemoMode){revalidatePath('/admin/content');revalidatePath('/');return{ok:true,demo:true};}const supabase=await createServerSupabaseClient();const{data,error}=await supabase.rpc('manage_home_event',{p_event_id:id,p_visible:Boolean(visible),p_rank:visible?Math.max(1,Math.min(99,Number(rank)||99)):null});if(error)return{ok:false,error:error.message};revalidatePath('/admin/content');revalidatePath('/');return{ok:true,data};}

export async function hardDeleteContent(type,id,reason){const viewer=await getViewer();if(!isSuperAdmin(viewer))return{ok:false,error:'Super Admin access required'};const cleaned=String(reason||'').trim();if(cleaned.length<10)return{ok:false,error:'Enter a deletion reason of at least 10 characters.'};if(isDemoMode)return{ok:true,demo:true};const supabase=await createServerSupabaseClient();const{data,error}=await supabase.rpc('hard_delete_content',{p_content_type:type,p_content_id:id,p_reason:cleaned});if(error)return{ok:false,error:error.message};['/admin/content','/admin/history','/','/opportunities','/events','/events/all','/announcements'].forEach(revalidatePath);return{ok:true,data};}
