'use client';
import { useState } from 'react';
import { manageContent } from './actions';

export default function ContentControls({ rows }) {
  const [items, setItems] = useState(rows); const [message, setMessage] = useState('');
  async function act(row, action, changes = {}) { setMessage(`${action}ing ${row.title}…`); const result = await manageContent(row.content_type, row.id, action, changes); if (!result.ok) { setMessage(result.error || 'Update failed.'); return; } setItems(current => current.map(item => item.id === row.id ? { ...item, ...changes, status: action === 'unpublish' ? 'unpublished' : action === 'archive' ? 'archived' : action === 'soft_delete' ? 'deleted' : action === 'restore' ? 'published' : item.status } : item)); setMessage('Content updated and audited.'); }
  return <div><p role="status" aria-live="polite" className="text-sm text-slate">{message}</p>{!items.length && <div className="card review-empty">No content records are available.</div>}<div className="review-card-list">{items.map(row => <EditableCard key={row.id} row={row} onAction={act} />)}</div></div>;
}

function EditableCard({ row, onAction }) {
  const [draft, setDraft] = useState({ title: row.title || '', organization: row.organization || row.org || row.source || '', description: row.description || row.body || '', source_url: row.source_url || row.link || '', category: row.category || 'General', priority: row.priority || 'standard', is_featured: Boolean(row.is_featured), featured_until: row.featured_until || '', expires_at: row.expires_at || '' });
  const editable = ['published', 'unpublished', 'archived'].includes(row.status);
  return <article className="card review-card"><div className="review-card-heading"><div><div className="eyebrow">{row.content_type} · {row.status}</div><h2>{row.title}</h2><p className="text-sm text-slate">{draft.organization || 'No organization recorded'}</p>{row.priority && <p className="text-xs text-slate">Priority: {row.priority}{row.is_featured ? ' · Featured' : ''}</p>}</div><div className="review-card-actions">{row.status === 'published' && <button className="chip" onClick={() => onAction(row, 'unpublish')}>Unpublish</button>}{['published', 'unpublished'].includes(row.status) && <button className="chip" onClick={() => onAction(row, 'archive')}>Archive</button>}{row.status !== 'deleted' && <button className="chip" onClick={() => onAction(row, 'soft_delete')}>Soft-delete</button>}{row.status === 'deleted' && <button className="gold-button" onClick={() => onAction(row, 'restore')}>Restore</button>}</div></div>{editable && <details className="review-details"><summary>Edit published details</summary><div className="content-edit-form"><label>Title<input value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></label><label>Organization/source<input value={draft.organization} onChange={e => setDraft({ ...draft, organization: e.target.value })} /></label><label>Description/body<textarea rows="4" value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label>{row.content_type === 'announcement' && <><label>Category<select value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value })}>{['College','C.O.D.E.','Department','Academic','Event','Student Organization','General'].map(value=><option key={value}>{value}</option>)}</select></label><label>Official source URL<input type="url" value={draft.source_url} onChange={e => setDraft({ ...draft, source_url: e.target.value })} /></label><label>Priority<select value={draft.priority} onChange={e => setDraft({ ...draft, priority: e.target.value })}><option>standard</option><option>leadership</option><option>code</option><option>campus</option></select></label><label><input type="checkbox" checked={draft.is_featured} onChange={e => setDraft({ ...draft, is_featured: e.target.checked })} /> Featured</label><label>Featured until<input type="date" value={draft.featured_until} onChange={e => setDraft({ ...draft, featured_until: e.target.value })} /></label><label>Expiry date<input type="date" value={draft.expires_at} onChange={e => setDraft({ ...draft, expires_at: e.target.value })} /></label></>}{row.content_type !== 'announcement' && <label>Source URL<input type="url" value={draft.source_url} onChange={e => setDraft({ ...draft, source_url: e.target.value })} /></label>}<button className="gold-button" onClick={() => onAction(row, 'edit', draft)}>Save audited edits</button></div></details>}</article>;
}
