import { getViewer,isAdmin,isSuperAdmin } from '../../../lib/auth';
import { createServerSupabaseClient,isDemoMode } from '../../../lib/supabaseServerClient';
import { sampleEvents,sampleOpportunities,sampleAnnouncements } from '../../../lib/sampleData';
import ContentManager from './ContentManager';
import ContentEditForms from './ContentEditForms';
import RecommendationAdmin from './RecommendationAdmin';
import { getFeatureRecommendations } from '../../../lib/recommendationData';
async function rows(){if(isDemoMode)return [...sampleEvents.slice(0,4).map(x=>({...x,content_type:'event',status:'published'})),...sampleOpportunities.slice(0,3).map(x=>({...x,content_type:'opportunity',status:'published'})),...sampleAnnouncements.map(x=>({...x,content_type:'announcement',status:'published'}))];const supabase=await createServerSupabaseClient();const tables=[['events','event'],['opportunities','opportunity'],['announcements','announcement']];const result=[];for(const [table,type] of tables){const{data}=await supabase.from(table).select('*').in('status',['published','unpublished','archived','deleted']).order('created_at',{ascending:false});result.push(...(data||[]).map(x=>({...x,content_type:type})));}return result;}
export default async function ContentPage(){const viewer=await getViewer();if(!viewer.user||!isAdmin(viewer))return <div className="auth-card"><h1>Administrator access required</h1><p>Content Management is restricted to administrators and super administrators.</p></div>;const contentRows=await rows();const featured=contentRows.filter(row=>row.is_featured&&row.status==='published');const published=contentRows.filter(row=>row.status==='published');const counts={opportunity:contentRows.filter(row=>row.content_type==='opportunity').length,event:contentRows.filter(row=>row.content_type==='event').length,announcement:contentRows.filter(row=>row.content_type==='announcement').length};return <div className="review-page workspace-subpage"><div className="workspace-page-heading"><div><div className="eyebrow">Workspace operations</div><h1>Content Management</h1><p>Manage published opportunities, events, and announcements. Every privileged action is audited.</p></div></div><div className="content-overview-grid"><section className="content-summary-card content-summary-compact" aria-label="Content summary"><div className="eyebrow">Content summary</div><div className="content-summary-total"><strong>{published.length}</strong><span>published</span></div><div className="content-summary-counts"><span>{counts.opportunity} opportunities</span><span>{counts.event} events</span><span>{counts.announcement} announcements</span></div></section><RecommendationAdmin rows={await getFeatureRecommendations()} featured={featured}/></div><ContentManager rows={contentRows} superAdmin={isSuperAdmin(viewer)}/><ContentEditForms rows={contentRows}/></div>}
