'use client';
import { useMemo,useState } from 'react';
import Link from 'next/link';
import { changeUserRole } from './actions';

export default function PeopleAccessManager({rows,requests,superAdmin}) {
  const [items,setItems]=useState(rows); const [search,setSearch]=useState(''); const [role,setRole]=useState(''); const [status,setStatus]=useState(''); const [message,setMessage]=useState('');
  const filtered=useMemo(()=>items.filter(row=>(!search||`${row.name||''} ${row.email||''} ${row.organization_department||''}`.toLowerCase().includes(search.toLowerCase()))&&(!role||row.role===role)&&(!status||row.status===status)),[items,search,role,status]);
  const pendingCount=requests.filter(request=>request.status==='pending').length;
  async function update(row,nextRole,nextStatus){setMessage(`Updating ${row.name||row.email}…`);const result=await changeUserRole(row.id,nextRole,nextStatus);if(!result.ok){setMessage(result.error||'Could not update access.');return;}setItems(current=>current.map(item=>item.id===row.id?{...item,role:nextRole,status:nextStatus}:item));setMessage('Access change completed and audited.');}
  return <section className="people-access-manager">
    <section className="people-requests-link" aria-label="Pending contributor requests"><div><span>{pendingCount}</span><p><strong>Contributor {pendingCount===1?'request':'requests'}</strong><small>{pendingCount?'Waiting for review':'Nothing awaiting review'}</small></p></div><Link href="/admin/committee">Open approvals →</Link></section>
    <div className="people-roster-heading"><div><div className="eyebrow">Access roster</div><h2>Approved and existing access</h2></div><a className="roster-export" href="/api/admin/access-requests/export">↓ Export Approved Roster</a></div>
    <div className="people-manager-controls"><label><span>Search name/email/organization</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search access records"/></label><label><span>Role</span><select value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option><option value="contributor">Contributor</option><option value="reviewer">Reviewer</option>{superAdmin&&<><option value="admin">Admin</option><option value="super_admin">Super admin</option></>}</select></label><label><span>Status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="needs_review">Needs review</option></select></label></div><p className="workspace-status" role="status" aria-live="polite">{message||`${filtered.length} access records shown.`}</p>
    <div className="people-access-grid">{filtered.map(row=><article className="people-access-row" key={row.id}><div><div className="eyebrow">{row.role} · {row.status}</div><h2>{row.name||'Name not provided'}</h2><p>{row.email} · {row.organization_department||'Organization not provided'}</p><small>Assigned {row.assigned_at?new Date(row.assigned_at).toLocaleDateString():'not recorded'}{row.assigned_by?` by ${row.assigned_by}`:''}</small></div><div className="people-access-actions">{(superAdmin||['contributor','reviewer'].includes(row.role))&&<><label><span className="sr-only">Role</span><select aria-label={`Role for ${row.name||row.email}`} value={row.role} onChange={e=>update(row,e.target.value,row.status)}><option value="contributor">Contributor</option><option value="reviewer">Reviewer</option>{superAdmin&&<><option value="admin">Admin</option><option value="super_admin">Super admin</option></>}</select></label><button className="chip" onClick={()=>update(row,row.role,row.status==='active'?'needs_review':'active')}>{row.status==='active'?'Deactivate':'Activate'}</button></>}</div></article>)}</div>{!filtered.length&&<div className="workspace-empty">No access records match these filters.</div>}
  </section>;
}
