'use client';
import { useMemo,useState } from 'react';
import Link from 'next/link';
import { cancelPersonInvitation, changeUserRole, removePerson, resendPersonInvitation } from './actions';

export default function PeopleAccessManager({rows,invitations=[],superAdmin,currentRoleId}) {
  const [items,setItems]=useState(rows); const [search,setSearch]=useState(''); const [role,setRole]=useState(''); const [status,setStatus]=useState(''); const [message,setMessage]=useState('');
  const [inviteItems,setInviteItems]=useState(()=>invitations.filter(item=>item.status==='pending')); const [cancelTarget,setCancelTarget]=useState(null); const [removeTarget,setRemoveTarget]=useState(null); const [removePersonTarget,setRemovePersonTarget]=useState(null);
  const filtered=useMemo(()=>items.filter(row=>(!search||`${row.name||''} ${row.email||''} ${row.organization_department||''}`.toLowerCase().includes(search.toLowerCase()))&&(!role||row.role===role)&&(!status||row.status===status)),[items,search,role,status]);
  async function update(row,nextRole,nextStatus){setMessage(`Updating ${row.name||row.email}…`);const result=await changeUserRole(row.id,nextRole,nextStatus);if(!result.ok){setMessage(result.error||'Could not update access.');return;}setItems(current=>current.map(item=>item.id===row.id?{...item,role:nextRole,status:nextStatus}:item));setMessage('Access change completed and audited.');}
  async function resend(invitation){setMessage(`Resending invitation to ${invitation.email}…`);const result=await resendPersonInvitation(invitation.id);setMessage(result.ok?'Invitation email sent.':result.error||'The invitation could not be resent.');}
  async function cancel(){const invitation=cancelTarget;if(!invitation)return;setMessage(`Canceling invitation for ${invitation.email}…`);const result=await cancelPersonInvitation(invitation.id);if(result.ok){setInviteItems(current=>current.filter(item=>item.id!==invitation.id));setMessage('Invitation canceled.');}else setMessage(result.error||'The invitation could not be canceled.');setCancelTarget(null);}
  async function removeAccess(){const row=removeTarget;if(!row)return;await update(row,row.role,'needs_review');setRemoveTarget(null);}
  async function confirmRemovePerson(){const row=removePersonTarget;if(!row)return;setMessage(`Removing ${row.name||row.email} from Hub access…`);const result=await removePerson(row.id);if(result.ok){setItems(current=>current.filter(item=>item.id!==row.id));setMessage('Person removed from the access roster. Historical Hub activity was preserved.');}else setMessage(result.error||'The person could not be removed.');setRemovePersonTarget(null);}
  return <section className="people-access-manager">
    {superAdmin&&inviteItems.length>0&&<section className="people-invitations"><div className="people-roster-heading"><div><div className="eyebrow">Pending invitations</div><h2>Waiting for first sign-in</h2></div></div><div className="people-access-grid">{inviteItems.map(invitation=><article className="people-access-row" key={invitation.id}><div><div className="eyebrow">Pending Invite</div><h2>{invitation.full_name||'Name not provided'}</h2><p>{invitation.email} · {invitation.affiliation_value||'No affiliation'}</p><small>{invitation.intended_role?.replace('_',' ')||'Contributor'} · Invited {new Date(invitation.invited_at).toLocaleDateString()} by {invitation.invited_by_name||'Super Admin'} · {invitation.last_delivery_status==='sent'?'Email sent':'Email needs attention'}</small></div><div className="people-access-actions"><button className="chip" onClick={()=>resend(invitation)}>Resend Invitation</button><button className="chip" onClick={()=>setCancelTarget(invitation)}>Cancel Invitation</button></div></article>)}</div></section>}
    <div className="people-roster-heading"><div><div className="eyebrow">Access roster</div><h2>Approved and existing access</h2></div><a className="roster-export" href="/api/admin/access-requests/export">↓ Export Approved Roster</a></div>
    <div className="people-manager-controls"><label><span>Search name/email/affiliation</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search access records"/></label><label><span>Role</span><select value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option><option value="contributor">Contributor</option><option value="reviewer">Reviewer</option>{superAdmin&&<><option value="admin">Admin</option><option value="super_admin">Super admin</option></>}</select></label><label><span>Status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="needs_review">Deactivated</option></select></label></div><p className="workspace-status" role="status" aria-live="polite">{message||`${filtered.length} access records shown.`}</p>
    <div className="people-access-grid">{filtered.map(row=><article className="people-access-row" key={row.id}><div><div className="eyebrow">{row.role} · {row.status==='needs_review'?'Deactivated':row.status}</div><h2>{row.name||'Name not provided'}</h2><p>{row.email} · {row.organization_department||'Affiliation not provided'}</p><small>Assigned {row.assigned_at?new Date(row.assigned_at).toLocaleDateString():'not recorded'}{row.assigned_by?` by ${row.assigned_by}`:''}</small></div><div className="people-access-actions">{(superAdmin||['contributor','reviewer'].includes(row.role))&&<><label><span className="sr-only">Role</span><select aria-label={`Role for ${row.name||row.email}`} value={row.role} onChange={e=>update(row,e.target.value,row.status)}><option value="contributor">Contributor</option><option value="reviewer">Reviewer</option>{superAdmin&&<><option value="admin">Admin</option><option value="super_admin">Super admin</option></>}</select></label>{row.status==='active'?<button className="chip" onClick={()=>setRemoveTarget(row)}>Deactivate</button>:<button className="chip" onClick={()=>update(row,row.role,'active')}>Reactivate</button>}{superAdmin&&row.id!==currentRoleId&&<button className="chip" onClick={()=>setRemovePersonTarget(row)}>Remove Person</button>}</>}</div></article>)}</div>{!filtered.length&&<div className="workspace-empty">No access records match these filters.</div>}
    {cancelTarget&&<div className="issue-report-backdrop"><div className="issue-report-dialog" role="dialog" aria-modal="true" aria-labelledby="cancel-invite-title"><div className="issue-report-form"><div className="issue-report-heading"><div><span>Pending invitation</span><h2 id="cancel-invite-title">Cancel this invitation?</h2></div></div><p>{cancelTarget.email} will no longer be able to activate access from this invitation. Its history will remain available for audit.</p><div className="invite-person-actions"><button className="outline-button" onClick={()=>setCancelTarget(null)}>Keep Invitation</button><button className="danger-button" onClick={cancel}>Cancel Invitation</button></div></div></div></div>}
    {removeTarget&&<div className="issue-report-backdrop"><div className="issue-report-dialog" role="dialog" aria-modal="true" aria-labelledby="remove-access-title"><div className="issue-report-form"><div className="issue-report-heading"><div><span>People &amp; Access</span><h2 id="remove-access-title">Remove access for {removeTarget.name||removeTarget.email}?</h2></div></div><p>This person will no longer be able to use protected Hub features until a Super Admin restores their access. Their identity, submissions, and audit history will remain preserved.</p><div className="invite-person-actions"><button className="outline-button" onClick={()=>setRemoveTarget(null)}>Cancel</button><button className="danger-button" onClick={removeAccess}>Remove Access</button></div></div></div></div>}
    {removePersonTarget&&<div className="issue-report-backdrop"><div className="issue-report-dialog" role="dialog" aria-modal="true" aria-labelledby="remove-person-title"><div className="issue-report-form"><div className="issue-report-heading"><div><span>People &amp; Access</span><h2 id="remove-person-title">Remove {removePersonTarget.name||removePersonTarget.email} from Hub access?</h2></div></div><p>They will be removed from the active access roster and will need a new invitation to regain Hub access. Historical Hub activity will be preserved.</p><div className="invite-person-actions"><button className="outline-button" onClick={()=>setRemovePersonTarget(null)}>Cancel</button><button className="danger-button" onClick={confirmRemovePerson}>Remove Person</button></div></div></div></div>}
  </section>;
}
