'use client';
import { useState } from 'react';
import { changeUserRole } from './actions';

export default function PeopleRoster({ rows, canManage }) {
  const [items, setItems] = useState(rows); const [message, setMessage] = useState('');
  async function update(row, role, status) { setMessage(`Updating ${row.name}…`); const result = await changeUserRole(row.id, role, status); if (!result.ok) { setMessage(result.error); return; } setItems(current => current.map(item => item.id === row.id ? { ...item, role, status } : item)); setMessage(`${row.name} updated.`); }
  return <div><p className="text-sm text-slate" role="status" aria-live="polite">{message}</p><div className="people-roster" role="region" aria-label="People and access roster">{!items.length && <div className="card review-empty"><h2>No people found</h2><p>Approved roles will appear here after provisioning.</p></div>}{items.map(row => <article className="card people-card" key={row.id}><div><div className="eyebrow">{row.role} · {row.status}</div><h2>{row.name || 'Name not provided'}</h2><p className="text-sm text-slate">{row.email} · {row.organization_department || 'Organization not provided'}</p><p className="people-meta">Assigned {row.assigned_at ? new Date(row.assigned_at).toLocaleDateString() : 'not recorded'}{row.assigned_by ? ` by ${row.assigned_by}` : ''} · Last submission {row.last_submission ? new Date(row.last_submission).toLocaleDateString() : 'none recorded'}</p></div>{canManage && (canManage.super || ['contributor', 'reviewer'].includes(row.role)) && <div className="people-actions"><label>Role<select aria-label={`Role for ${row.name || row.email}`} value={row.role} onChange={e => update(row, e.target.value, row.status)}><option value="contributor">Contributor</option><option value="reviewer">Reviewer</option>{canManage.super && <><option value="admin">Admin</option><option value="super_admin">Super admin</option></>}</select></label><button className="chip" onClick={() => update(row, row.role, row.status === 'active' ? 'needs_review' : 'active')}>{row.status === 'active' ? 'Deactivate' : 'Activate'}</button></div>}</article>)}</div></div>;
}
