import Link from 'next/link';
import { getOpportunities, getEvents, getAnnouncements } from '../lib/data';
export default async function HomePage(){
 const [opportunities,events,announcements]=await Promise.all([getOpportunities(),getEvents(),getAnnouncements()]);
 return <><section className="hero"><img className="hero-crest" src="/code-crest.png" alt="" /><div className="hero-inner"><div className="eyebrow">Prairie View A&amp;M University</div><h1>Excellence finds every <em>Panther</em> here.</h1><p>One trusted place for engineering opportunities, college events, student-organization activity, and announcements that move students forward.</p><div className="hero-actions"><Link className="gold-button" href="/opportunities">Explore opportunities</Link><Link className="outline-button" href="/events">View calendar</Link></div></div></section>
 <HomeSection title="Upcoming events" href="/events/all">{events.slice(0,3).map(e=><Link className="card" href={'/events/'+e.id} key={e.id}><div className="eyebrow">{new Date(e.date).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</div><h3>{e.title}</h3><p>{e.time} · {e.location}</p></Link>)}</HomeSection>
 <HomeSection title="Featured opportunities" href="/opportunities">{opportunities.slice(0,3).map(o=><Link className="card" href={'/opportunities/'+o.id} key={o.id}><div className="eyebrow">{o.type}{o.paid?' · Paid/Funded':''}</div><h3>{o.title}</h3><p>{o.org}</p><small>Deadline {new Date(o.deadline).toLocaleDateString()}</small></Link>)}</HomeSection>
 <HomeSection title="Recent announcements" href="/announcements">{announcements.slice(0,3).map(a=><article className="card" key={a.id}><div className="eyebrow">{a.source}</div><h3>{a.title}</h3><p>{a.body}</p></article>)}</HomeSection></>;
}
function HomeSection({title,href,children}){return <section className="section"><div className="section-title"><h2>{title}</h2><Link className="view-all" href={href}>View all →</Link></div><div className="card-grid">{children}</div></section>}
