'use client';

import { useEffect, useState, useTransition } from 'react';
import { dismissRejectedSubmissionAction, resubmitCorrectionAction } from '../app/panther-submit/statusActions';
import { DEADLINE_TYPES, OPPORTUNITY_COMPENSATION_TYPES } from '../lib/opportunityOptions';

const STATUS_LABELS = { pending: 'Pending Review', needs_correction: 'Needs Correction', resubmitted: 'Resubmitted', published: 'Published', rejected: 'Rejected', archived: 'Archived' };
const EDIT_FIELDS = {
  event: [['title', 'Title'], ['org', 'Hosting organization'], ['date', 'Date'], ['end_date', 'End date'], ['time', 'Time'], ['location', 'Location'], ['description', 'Description'], ['registration_link', 'Registration link'], ['contact_name', 'Contact name'], ['contact_email', 'Contact email']],
  opportunity: [['title', 'Title'], ['org', 'Organization'], ['deadline_type', 'Deadline type'], ['deadline', 'Application deadline'], ['posted_date', 'Original posting date'], ['compensation_type', 'Compensation'], ['location', 'Location'], ['description', 'Description'], ['eligibility', 'Eligibility'], ['link', 'Application link'], ['contact_name', 'Contact name'], ['contact_email', 'Contact email']],
  announcement: [['title', 'Title'], ['source', 'Source'], ['body', 'Announcement'], ['source_url', 'Source link'], ['category', 'Category']],
};
function displayDate(value) { if (!value) return 'Not recorded'; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? 'Not recorded' : parsed.toLocaleDateString(); }
function fieldInput(field, label, values, updateValue) {
  if (field === 'deadline' && values.deadline_type !== 'specific_date') return null;
  if (field === 'deadline_type') return <label key={field}><span>{label}</span><select value={values[field] || 'specific_date'} onChange={(event) => updateValue(field, event.target.value)}>{DEADLINE_TYPES.slice(0, 2).map(([value, optionLabel]) => <option key={value} value={value}>{optionLabel}</option>)}</select></label>;
  if (field === 'compensation_type') return <label key={field}><span>{label}</span><select required value={values[field] || ''} onChange={(event) => updateValue(field, event.target.value)}><option value="">Choose compensation</option>{OPPORTUNITY_COMPENSATION_TYPES.map((value) => <option key={value} value={value}>{value}</option>)}</select></label>;
  const multiline = field === 'description' || field === 'eligibility' || field === 'body';
  return <label key={field}><span>{label}</span>{multiline ? <textarea rows="4" value={values[field] || ''} onChange={(event) => updateValue(field, event.target.value)} /> : <input type={field.includes('date') || field === 'deadline' ? 'date' : field.includes('email') ? 'email' : field.includes('link') || field === 'source_url' ? 'url' : 'text'} value={values[field] || ''} onChange={(event) => updateValue(field, event.target.value)} />}</label>;
}
export default function SubmissionStatusPanel({ submissions = [] }) {
  const [items, setItems] = useState(submissions); const [editing, setEditing] = useState(null); const [values, setValues] = useState({}); const [message, setMessage] = useState(''); const [busy, startTransition] = useTransition(); const [filter,setFilter]=useState('all'); const [limit,setLimit]=useState(10);
  useEffect(() => { setItems(submissions); }, [submissions]);
  function beginEdit(item) { setEditing(item.content_id); setValues(item.editable || {}); setMessage(''); }
  function updateValue(field, value) { setValues((current) => ({ ...current, [field]: value, ...(field === 'deadline_type' && value !== 'specific_date' ? { deadline: '' } : {}) })); }
  function resubmit(item) { setMessage('Saving your corrections…'); startTransition(async () => { const result = await resubmitCorrectionAction({ contentType: item.content_type, contentId: item.content_id, values }); if (result.ok) { setItems((current) => current.map((candidate) => candidate.content_id === item.content_id ? { ...candidate, status: 'resubmitted', editable: values, updated_at: new Date().toISOString() } : candidate)); setEditing(null); setMessage('Your corrections were resubmitted for review. The same submission and its history were preserved.'); } else setMessage(result.error || 'Your corrections could not be resubmitted.'); }); }
  function dismiss(item) { startTransition(async () => { const result = await dismissRejectedSubmissionAction(item.content_type, item.content_id); if (result.ok) { setItems((current) => current.filter((candidate) => candidate.content_id !== item.content_id)); setMessage('The rejected submission was removed from your dashboard. Its review history was preserved.'); } else setMessage(result.error || 'The submission could not be dismissed.'); }); }
  const sorted=[...items].sort((a,b)=>new Date(b.updated_at||b.created_at)-new Date(a.updated_at||a.created_at));
  const attention=sorted.filter(item=>item.status==='needs_correction');
  const matches=(item,value)=>value==='all'||(value==='attention'&&item.status==='needs_correction')||(value==='review'&&['pending','resubmitted'].includes(item.status))||(value==='published'&&item.status==='published')||(value==='rejected'&&item.status==='rejected');
  const counts={all:sorted.length,attention:attention.length,review:sorted.filter(item=>['pending','resubmitted'].includes(item.status)).length,published:sorted.filter(item=>item.status==='published').length,rejected:sorted.filter(item=>item.status==='rejected').length};
  const history=sorted.filter(item=>item.status!=='needs_correction'&&matches(item,filter));
  const renderCard=(item)=>{const submitted=item.created_at||item.submitted_at||item.updated_at;const typeLabel=item.content_type==='opportunity'?'Opportunity':item.content_type==='event'?'Event':'Announcement';return <article key={`${item.content_type}-${item.content_id}`} className="submission-status-card"><div className="submission-status-heading"><div><span className={`submission-status-badge status-${item.status}`}>{STATUS_LABELS[item.status]||item.status}</span><h3>{item.title||'Untitled submission'}</h3><small>{typeLabel} · Submitted {displayDate(submitted)} · Updated {displayDate(item.updated_at)}</small></div>{item.status==='published'&&<a href={`/${item.content_type==='opportunity'?'opportunities':item.content_type==='event'?'events':'announcements'}/${item.content_id}`}>View published item</a>}</div>{item.status==='pending'&&<p className="submission-status-help">Your submission is in the Review Queue and is not public yet.</p>}{item.status==='resubmitted'&&<p className="submission-status-help">Your corrections are In Review in the active Review Queue.</p>}{item.status==='published'&&<p className="submission-status-help">Students can now view this item.</p>}{item.editable&&<details className="submission-status-details"><summary>View submitted details</summary><dl>{Object.entries(item.editable).filter(([,value])=>value!==null&&value!=='').map(([field,value])=><div key={field}><dt>{field.replaceAll('_',' ')}</dt><dd>{String(value)}</dd></div>)}</dl></details>}{item.reviewer_note&&<div className="submission-reviewer-note"><strong>{item.status==='rejected'?'Reason':'Changes requested'}</strong><p>{item.reviewer_note}</p></div>}{item.status==='needs_correction'&&editing!==item.content_id&&<button type="button" className="gold-button" onClick={()=>beginEdit(item)}>Edit &amp; Resubmit</button>}{item.status==='needs_correction'&&editing===item.content_id&&<div className="submission-correction-form"><h4>Edit submission details</h4><p>Update the requested fields below. Your original source and review history remain attached.</p>{(EDIT_FIELDS[item.content_type]||[]).map(([field,label])=>fieldInput(field,label,values,updateValue))}<div className="submission-correction-actions"><button type="button" className="outline-button" onClick={()=>setEditing(null)}>Cancel</button><button type="button" className="gold-button" disabled={busy} onClick={()=>resubmit(item)}>{busy?'Resubmitting…':'Resubmit for review'}</button></div></div>}{item.status==='rejected'&&<button type="button" className="outline-button" disabled={busy} onClick={()=>dismiss(item)}>Dismiss from dashboard</button>}</article>};
  return <section id="submission-status" className="submission-status-panel" aria-labelledby="submission-status-title"><div><div className="eyebrow">Your submissions</div><h2 id="submission-status-title">Submission status</h2><p>Track what is waiting for review, published, or needs your attention.</p></div><p className="workspace-status" role="status" aria-live="polite">{message}</p>{items.length===0?<p className="submission-status-empty">You have no saved submissions yet.</p>:<>{attention.length>0&&<section className="submission-action-needed" aria-labelledby="action-needed-title"><div className="eyebrow">Action needed</div><h3 id="action-needed-title">Please update {attention.length===1?'this submission':'these submissions'}</h3><div className="submission-status-list">{attention.map(renderCard)}</div></section>}<div className="submission-filter-tabs" role="tablist" aria-label="Submission status filters">{[['all','All'],['attention','Action Needed'],['review','In Review'],['published','Published'],['rejected','Rejected']].map(([value,label])=><button key={value} type="button" role="tab" aria-selected={filter===value} className={filter===value?'active':''} onClick={()=>{setFilter(value);setLimit(10);}}>{label} <span>{counts[value]}</span></button>)}</div>{filter==='attention'?<p className="submission-status-empty">Action Needed items are shown above.</p>:<div className="submission-status-list">{history.slice(0,limit).map(renderCard)}{!history.length&&<p className="submission-status-empty">No submissions match this filter.</p>}{history.length>limit&&<button type="button" className="outline-button submission-load-more" onClick={()=>setLimit(current=>current+10)}>Load more</button>}</div>}</>}</section>;
}
