'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';

const sections = [['home','01','Home'],['who-we-are','02','Who We Are'],['what-we-do','03','What We Do'],['our-promise','04','Our Promise'],['get-involved','05','Get Involved']];
const functions = [['network','Centralize','Opportunities, events & resources'],['voice','Advocate','Student voice & representation'],['link','Connect','Alumni, sponsors & industry'],['nodes','Collaborate','Across engineering disciplines']];
const principles = [['01','Student-Centered','We listen before we act.'],['02','Accessible','Information and opportunity should be easier to find.'],['03','Collaborative','Students, faculty, alumni, sponsors, and College leadership move further together.'],['04','Impact-Driven','What we build should create something students can actually use.']];

export default function WhoIsCodeExperience({ showWorkspace = false }) {
  const [active, setActive] = useState('home');
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => {
    const observer = new IntersectionObserver(entries => { const visible = entries.filter(entry => entry.isIntersecting).sort((a,b) => b.intersectionRatio-a.intersectionRatio)[0]; if (visible) setActive(visible.target.id); }, { rootMargin:'-25% 0px -55%', threshold:[.05,.3,.6] });
    sections.forEach(([id]) => { const element=document.getElementById(id); if(element) observer.observe(element); });
    return () => observer.disconnect();
  }, []);
  useEffect(() => { const onKey=event => { if(event.key==='Escape') setMenuOpen(false); }; document.addEventListener('keydown',onKey); return () => document.removeEventListener('keydown',onKey); }, []);

  return <div className="code-about-page">
    <a className="code-about-skip" href="#who-we-are">Skip to story</a>
    <div className="code-about-topbar"><a href="#home" className="code-about-mini-brand" aria-label="C.O.D.E. page home"><strong>C.O.D.E.</strong><span>Council of Distinguished Engineers</span></a><button type="button" className="code-about-menu-button" aria-expanded={menuOpen} aria-controls="code-about-menu" onClick={() => setMenuOpen(value=>!value)}><span>{menuOpen?'Close':'Explore the Hub'}</span><b aria-hidden="true">{menuOpen?'×':'☰'}</b></button>{menuOpen&&<nav id="code-about-menu" className="code-about-menu" aria-label="Engineering Hub"><Link href="/" onClick={()=>setMenuOpen(false)}>Home</Link><Link href="/events" onClick={()=>setMenuOpen(false)}>Events</Link><Link href="/opportunities" onClick={()=>setMenuOpen(false)}>Opportunities</Link><Link href="/announcements" onClick={()=>setMenuOpen(false)}>Announcements</Link>{showWorkspace&&<Link href="/admin" onClick={()=>setMenuOpen(false)}>Workspace</Link>}</nav>}</div>
    <nav className="code-about-section-rail" aria-label="Page sections">{sections.map(([id,number,label])=><a key={id} href={`#${id}`} className={active===id?'is-active':''} aria-current={active===id?'location':undefined}><span>{number}</span>{label}</a>)}</nav>
    <aside className="code-about-connect" aria-label="Connect with C.O.D.E."><span>Connect with C.O.D.E.</span><a href="https://www.instagram.com/pvamucode/" target="_blank" rel="noreferrer" aria-label="C.O.D.E. on Instagram"><SocialIcon type="instagram"/></a><a href="mailto:code@pvamu.edu" aria-label="Email C.O.D.E."><SocialIcon type="email"/></a><span className="code-about-linkedin" title="LinkedIn — Coming Soon"><SocialIcon type="linkedin"/><small>Coming soon</small></span></aside>

    <section id="home" className="code-about-hero"><div className="code-about-hero-copy"><div className="code-about-institution">Prairie View A&amp;M University<span>Roy G. Perry College of Engineering</span></div><p className="code-about-eyebrow">Students. Opportunity. Community. Impact.</p><h1>Who Is<br/><em>C.O.D.E.?</em></h1><p className="code-about-lede">The Council of Distinguished Engineers is the student-led engineering council within the Roy G. Perry College of Engineering at Prairie View A&amp;M University.</p><div className="code-about-actions"><a className="code-about-primary" href="#who-we-are">Our Story <span aria-hidden="true">→</span></a><a href="#what-we-do">What We Do</a><a href="#get-involved">Get Involved</a></div></div><div className="code-about-crest"><div aria-hidden="true"/><Image src="/code-crest.png" alt="Council of Distinguished Engineers crest — Prairie View A&M University, established 2026" width={560} height={560} priority/></div></section>

    <section id="who-we-are" className="code-about-light code-about-story"><div><p className="code-about-label">01. Who We Are</p><h2>Students.<br/>Opportunity.<br/>Community. <em>Impact.</em></h2><p>C.O.D.E. is the student-led engineering council within the Roy G. Perry College of Engineering at Prairie View A&amp;M University. We serve as a central hub for opportunities, resources, communication, and advocacy — building a stronger, more connected engineering community.</p><div className="code-about-markers"><span>Students first</span><span>A stronger community</span><span>A brighter tomorrow</span></div></div><div className="code-about-purpose"><Image src="/images/encarb-secondary.jpg" alt="Roy G. Perry College of Engineering at Prairie View A&M University" width={760} height={540}/><div><span>One College.</span><span>Many disciplines.</span><span>A shared purpose.</span><p>We represent engineering students across departments, uniting ideas, perspectives, and opportunities to elevate the entire College.</p></div></div></section>

    <section id="what-we-do" className="code-about-dark code-about-functions"><div className="code-about-section-heading"><p className="code-about-label">02. What We Do</p><h2>From Information<br/>to <em>Impact.</em></h2><p>C.O.D.E. creates access, builds connections, and empowers engineering students through programming, communication, and collaboration.</p></div><div className="code-about-function-grid">{functions.map(([icon,title,description])=><article key={title}><FunctionIcon type={icon}/><h3>{title}</h3><p>{description}</p></article>)}</div></section>

    <section id="our-promise" className="code-about-light code-about-promise"><div><p className="code-about-label">03. Our Promise</p><h2>Every discipline.<br/>Every classification.<br/><em>Every engineer.</em></h2><p>A stronger engineering tomorrow.</p></div><div className="code-about-principles">{principles.map(([number,title,body])=><article key={number}><span>{number}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></section>

    <section id="get-involved" className="code-about-dark code-about-next"><div className="code-about-next-photo" aria-hidden="true"><Image src="/images/pvamu-encarb-hero.jpg" alt="" fill sizes="100vw"/></div><div className="code-about-next-overlay" aria-hidden="true"/><div><p className="code-about-label">04. Be Part of What’s Next</p><h2>One Hub.<br/>A Stronger <em>Tomorrow.</em></h2><p>Explore opportunities. Get involved. Help shape what’s next for PVAMU engineers.</p><div className="code-about-actions"><Link className="code-about-primary" href="/opportunities">Explore Opportunities <span aria-hidden="true">→</span></Link><Link href="/events">View Events</Link><Link href="/panther-submit">Submit an Opportunity</Link></div></div></section>
    <footer className="code-about-footer"><div><strong>C.O.D.E.</strong><span>Council of Distinguished Engineers</span></div><p>Prairie View A&amp;M University<br/>Roy G. Perry College of Engineering</p><p>Engineers today.<br/><b>A stronger tomorrow.</b></p></footer>
  </div>;
}

function SocialIcon({type}) { if(type==='instagram') return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1"/></svg>; if(type==='email') return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></svg>; return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M8 10v7M8 7v.2M12 17v-4a3 3 0 0 1 6 0v4M12 10v7"/></svg>; }
function FunctionIcon({type}) { if(type==='network') return <svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="24" cy="24" r="6"/><circle cx="9" cy="13" r="4"/><circle cx="39" cy="13" r="4"/><circle cx="9" cy="37" r="4"/><circle cx="39" cy="37" r="4"/><path d="m13 15 6 6m16-6-6 6m-16 14 6-7m16 7-6-7"/></svg>; if(type==='voice') return <svg viewBox="0 0 48 48" aria-hidden="true"><path d="M9 27h7l15 9V12l-15 9H9v6Z"/><path d="M36 19c4 3 4 7 0 10M16 27v9"/></svg>; if(type==='link') return <svg viewBox="0 0 48 48" aria-hidden="true"><path d="m20 30-3 3a8 8 0 1 1-11-11l7-7a8 8 0 0 1 11 0M28 18l3-3a8 8 0 1 1 11 11l-7 7a8 8 0 0 1-11 0M17 31l14-14"/></svg>; return <svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="24" cy="9" r="4"/><circle cx="10" cy="35" r="4"/><circle cx="38" cy="35" r="4"/><path d="M22 13 12 31m14-18 10 18M14 35h20"/></svg>; }
