import { getViewer, isSuperAdmin } from '../../../lib/auth';
import { getSystemInsights } from '../../../lib/systemInsightsData';
import { getParserActivity, getParserFeedbackMetrics } from '../../../lib/parserFeedbackData';

const text = (value) => String(value || '').replaceAll('_', ' ');
const displayDate = (value) => value ? new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Not completed';

function activityOutcome(activity) {
  const failedSources = activity.sources.filter((source) => source.status === 'failed');
  const pendingSources = activity.sources.filter((source) => ['pending', 'processing'].includes(source.status));
  if (failedSources.length) return { tone: 'failed', label: 'Extraction failed', description: failedSources.flatMap((source) => source.warnings).filter(Boolean).join(' ') || 'The source could not be processed automatically.' };
  if (activity.state === 'failed') return { tone: 'failed', label: 'Submission failed', description: activity.extractedFields.length ? `Extraction produced ${activity.extractedFields.length} field suggestions, but the final submission did not complete.` : 'The intake stopped before a completed submission was created.' };
  if (activity.state === 'submitted') return { tone: 'success', label: 'Submitted', description: activity.extractedFields.length ? `${activity.extractedFields.length} fields were extracted before submission.` : 'The submission completed with manual entry or no saved field suggestions.' };
  if (pendingSources.length) return { tone: 'incomplete', label: 'Incomplete source processing', description: 'The source never reached a final processing state. The workflow may have been interrupted.' };
  return { tone: 'incomplete', label: 'Incomplete workflow', description: activity.extractedFields.length ? `${activity.extractedFields.length} fields were extracted, but the workflow did not reach submission.` : 'No extracted fields or completed submission were recorded. The workflow may have been abandoned.' };
}

function ParserActivity({ activities }) {
  if (activities === null) return <section className="system-insights-parser-activity"><div className="eyebrow">Parser activity</div><p className="workspace-status">Parser activity is currently unavailable. Submission processing remains usable.</p></section>;
  return <section className="system-insights-parser-activity">
    <header><div><div className="eyebrow">Parser activity</div><h2>Recent extraction attempts</h2><p>Private Super Admin diagnostics. Source text and extracted values are intentionally not shown.</p></div><span>{activities.length} recent attempt{activities.length === 1 ? '' : 's'}</span></header>
    {!activities.length ? <div className="workspace-empty">No extraction activity has been recorded.</div> : <div className="parser-activity-list">{activities.map((activity) => { const outcome = activityOutcome(activity); return <article className={`parser-activity-card parser-activity-${outcome.tone}`} key={activity.id}>
      <div className="parser-activity-heading"><div><span className="parser-activity-status">{outcome.label}</span><h3>{text(activity.contentType)} extraction</h3><p>{displayDate(activity.createdAt)} · {activity.submitter}</p></div><span>{activity.sources.map((source) => text(source.type)).join(' + ') || 'No source retained'}</span></div>
      <p className="parser-activity-description">{outcome.description}</p>
      <dl className="parser-activity-facts"><div><dt>Workflow state</dt><dd>{text(activity.state)}</dd></div><div><dt>Submitted</dt><dd>{displayDate(activity.submittedAt)}</dd></div><div><dt>Extracted fields</dt><dd>{activity.extractedFields.length ? activity.extractedFields.map(text).join(', ') : 'None recorded'}</dd></div><div><dt>Needs verification</dt><dd>{activity.reviewFields.length ? activity.reviewFields.map(text).join(', ') : 'None recorded'}</dd></div></dl>
      <details><summary>View parser details</summary><div className="parser-activity-details"><div><strong>Sources</strong>{activity.sources.length ? <ul>{activity.sources.map((source, index) => <li key={`${activity.id}-${index}`}><span>{source.filename || text(source.type)}</span><small>{text(source.status)}{source.mimeType ? ` · ${source.mimeType}` : ''}</small>{source.warnings.map((warning) => <p key={warning}>{warning}</p>)}</li>)}</ul> : <p>No source record was retained.</p>}</div><div><strong>Parser</strong><p>{activity.provider || 'Not recorded'}{activity.parserVersion ? ` · ${activity.parserVersion}` : ''}</p>{activity.reviewReasons.map((reason) => <p key={reason}>{reason}</p>)}</div></div></details>
      <div className="parser-activity-feedback"><strong>Parser review</strong>{activity.feedback ? <><span>{text(activity.feedback.rating)}</span><p>{activity.feedback.note || 'No written description was provided.'}</p>{activity.feedback.issueFields.length ? <small>Fields marked: {activity.feedback.issueFields.map(text).join(', ')}</small> : null}</> : <p>No parser feedback was submitted for this attempt.</p>}</div>
    </article>; })}</div>}
  </section>;
}

export default async function SystemInsightsPage() { const viewer=await getViewer(); if(!viewer.user||!isSuperAdmin(viewer))return <div className="workspace-auth-card"><h1>Super Admin access required</h1><p>System Insights is restricted to the Super Admin role.</p></div>; const[insights,parserFeedback,parserActivity]=await Promise.all([getSystemInsights(),getParserFeedbackMetrics(),getParserActivity()]); const feedback=parserFeedback.all||{}; return <div className="workspace-overview"><div className="workspace-page-heading"><div><div className="eyebrow">Current system state</div><h1>System Insights</h1><p>Operational counts from the live Hub database. Zero means zero; unavailable data is labeled.</p></div></div><div className="system-insights-grid">{Object.entries({Overview:insights.overview,Security:insights.security,'Content Health':insights.content,Operations:insights.operations}).map(([title,values])=><section key={title}><div className="eyebrow">{title}</div>{Object.entries(values).map(([label,value])=><div className="system-insight-row" key={label}><span>{label}</span><strong>{Number.isFinite(value)?value:'Unavailable'}</strong></div>)}</section>)}</div><section className="system-insights-parser-feedback"><div className="eyebrow">Parser quality feedback</div><p className="text-sm text-slate">Super Admin notes about extraction strengths, missed fields, and manual corrections.</p><div className="system-insight-row"><span>Feedback entries</span><strong>{feedback.total??0}</strong></div><div className="system-insight-row"><span>Ratings</span><strong>{Object.entries(feedback.ratings||{}).map(([key,value])=>`${key.replaceAll('_',' ')}: ${value}`).join(' · ')||'None yet'}</strong></div><div className="system-insight-row"><span>Fields needing attention</span><strong>{Object.entries(feedback.issues||{}).map(([key,value])=>`${key.replaceAll('_',' ')}: ${value}`).join(' · ')||'None yet'}</strong></div></section><ParserActivity activities={parserActivity}/>{insights.demo&&<p className="workspace-status">Demo mode is active; no operational values are fabricated.</p>}</div>; }
