export const FALL_2026_CALENDAR_URL =
  'https://www.pvamu.edu/registrar/academic-calendars/fall-2026-full-term-16-week-session/';

const academicDates = [
  ['sap-appeal-deadline', 'Financial Aid SAP Appeal Deadline', '2026-08-24',
    'Deadline to submit a Financial Aid Satisfactory Academic Progress appeal for Fall 2026.'],
  ['first-class-day', 'First Class Day', '2026-08-24',
    'The first day of classes for the Fall 2026 full-term session.', { type: 'Academic milestone' }],
  ['late-registration-undergraduate', 'Undergraduate Late Registration Begins', '2026-08-24',
    'Late registration and the $50 late-registration fee period for undergraduate students.', { end_date: '2026-08-29' }],
  ['late-registration-graduate', 'Graduate and Doctoral Late Registration Begins', '2026-08-24',
    'Late registration and the $50 late-registration fee period for graduate and doctoral students.', { end_date: '2026-09-01' }],
  ['attendance-reporting', 'Attendance Reporting Period Begins', '2026-08-24',
    'Students who do not attend during this period may have courses removed and financial aid reduced or cancelled.', { end_date: '2026-09-02' }],
  ['tuition-fees-due', 'Tuition and Fees Payment Due', '2026-09-02', 'Fall 2026 tuition and fees payment due date.'],
  ['labor-day', 'Labor Day Holiday', '2026-09-07',
    'University closed. This date is subject to approval by The Texas A&M University System Board of Regents and may change.', { type: 'University closure' }],
  ['financial-aid-refunds', 'Financial Aid Refunds Begin', '2026-09-07',
    'Financial aid refunds begin for the Fall 2026 full-term session.', { type: 'Academic milestone' }],
  ['census-date', '12th Class Day and Census Date', '2026-09-09',
    'Official 12th class day and census date for the Fall 2026 full-term session.', { type: 'Academic milestone' }],
  ['drop-without-record', 'Final Day to Drop Without an Academic Record', '2026-09-09',
    'Final day to drop or withdraw from courses without an academic record. A financial record will still exist.'],
  ['withdrawal-with-record', 'Withdrawal With an Academic Record Begins', '2026-09-10',
    'Withdrawal from courses with an academic record of W begins.', { type: 'Academic milestone' }],
  ['nonpayment-drop', 'Drop for Non-Payment of Tuition and Fees', '2026-09-15',
    'Students with unpaid tuition and fees may be dropped at 5:00 p.m.', { time: '5:00 PM' }],
  ['twentieth-class-day', '20th Class Day', '2026-09-21',
    'Official 20th class day for the Fall 2026 full-term session.', { type: 'Academic milestone' }],
  ['major-change-deadline', 'Last Day to Change Major', '2026-09-21',
    'Last day to change a major for the current academic term.'],
  ['non-class-day', 'Student and Faculty Non-Class Day', '2026-10-12',
    'No classes are scheduled for students or faculty.', { type: 'Academic milestone' }],
  ['midsemester-exams', 'Mid-Semester Examination Period Begins', '2026-10-13',
    'The Fall 2026 mid-semester examination period runs through October 17.', { end_date: '2026-10-17', type: 'Academic milestone' }],
  ['midsemester-grades', 'Mid-Semester Grades Due', '2026-10-21', 'Mid-semester grades are due.'],
  ['graduation-ceremony-application', 'Fall Graduation Ceremony Application Deadline', '2026-11-01',
    'Final date to apply for Fall 2026 graduation with ceremony participation.'],
  ['degree-conferral-opens', 'Degree-Conferral-Only Graduation Application Opens', '2026-11-02',
    'Applications open for Fall 2026 degree conferral only, without ceremony participation or a program listing.', { type: 'Academic milestone' }],
  ['spring-registration-special', 'Spring 2027 Priority Registration: Special Populations', '2026-11-02',
    'Priority registration begins for eligible special populations.', { type: 'Registration' }],
  ['spring-registration-graduate-senior', 'Spring 2027 Priority Registration: Graduate Students and Seniors', '2026-11-03',
    'Priority registration for doctoral, master’s, post-baccalaureate, and senior students.', { type: 'Registration' }],
  ['spring-registration-junior', 'Spring 2027 Priority Registration: Juniors', '2026-11-04',
    'Priority registration for junior students.', { type: 'Registration' }],
  ['spring-registration-sophomore', 'Spring 2027 Priority Registration: Sophomores', '2026-11-05',
    'Priority registration for sophomore students.', { type: 'Registration' }],
  ['spring-registration-freshman', 'Spring 2027 Priority Registration: Freshmen', '2026-11-06',
    'Priority registration for freshman students.', { type: 'Registration' }],
  ['spring-registration-all', 'Spring 2027 Registration Opens to All Students', '2026-11-07',
    'Registration opens to all students for Spring 2027 and the December/January Mini-Mester.', { type: 'Registration' }],
  ['withdrawal-deadline', 'Final Day to Withdraw With an Academic Record', '2026-11-17',
    'Final day to withdraw from a course or the university with an academic record of W.'],
  ['thanksgiving', 'Thanksgiving Holiday', '2026-11-26',
    'University closed for the Thanksgiving holiday through November 27.', { end_date: '2026-11-27', type: 'University closure' }],
  ['last-class-day', 'Last Class Day', '2026-11-30',
    'The last class day for the Fall 2026 full-term session.', { type: 'Academic milestone' }],
  ['study-day', 'Study Day', '2026-12-01', 'No classes are in session.', { type: 'Academic milestone' }],
  ['tuition-rebate-deadline', 'Graduating Undergraduate Tuition Rebate Deadline', '2026-12-01',
    'Final day for graduating undergraduates to submit the Fall 2026 tuition rebate application.'],
  ['degree-conferral-deadline', 'Degree-Conferral-Only Graduation Application Deadline', '2026-12-01',
    'Final day to apply for Fall 2026 degree conferral only, without ceremony participation or a program listing.'],
  ['final-exams', 'Final Examinations Begin', '2026-12-02',
    'Fall 2026 final examinations run through December 9.', { end_date: '2026-12-09', type: 'Academic milestone' }],
  ['graduation-candidate-grades', 'Final Grades Due for Graduation Candidates', '2026-12-09',
    'Final grades for graduation candidates are due by 11:59 p.m.', { time: '11:59 PM' }],
  ['graduate-commencement', 'Graduate Commencement', '2026-12-10',
    'Fall 2026 graduate commencement ceremony.', { type: 'Commencement' }],
  ['undergraduate-commencement', 'Undergraduate Commencement', '2026-12-11',
    'Fall 2026 undergraduate commencement ceremony.', { type: 'Commencement' }],
  ['all-final-grades', 'Final Grades Due for All Other Students', '2026-12-15',
    'Final grades for all remaining students are due by 11:59 p.m.', { time: '11:59 PM' }],
  ['winter-break', 'Winter Break Begins', '2026-12-24',
    'University closed for winter break through January 1, 2027.', { end_date: '2027-01-01', type: 'University closure' }],
];

export const fall2026AcademicEvents = academicDates.map(([id, title, date, description, overrides = {}]) => ({
  id: 'pvamu-fall-2026-' + id,
  title,
  date,
  description,
  type: 'Academic deadline',
  category: 'Key Dates & Milestones',
  majors: ['All majors'],
  time: 'All day',
  location: 'Prairie View A&M University',
  org: 'PVAMU Office of the Registrar',
  contact_name: 'PVAMU Office of the Registrar',
  contact_email: '',
  verified: true,
  source_name: 'PVAMU Fall 2026 Academic Calendar',
  source_url: FALL_2026_CALENDAR_URL,
  source_last_updated: '2026-03-25',
  ...overrides,
}));
