// Sample data shown when the app is running in demo mode (no Supabase
// credentials configured yet). Once Supabase is connected, all of this
// is replaced by real database queries -- see lib/data.js.

export const MAJORS = [
  'All majors',
  'Information Technology',
  'Chemical Engineering',
  'Civil Engineering',
  'Computer Engineering',
  'Computer Science',
  'Cybersecurity',
  'Data Analytics',
  'Electrical Engineering',
  'Mechanical Engineering',
];

// A tiny inline "flyer" placeholder so the "View original flyer" thumbnail
// has something to show in demo mode without any external image host.
const DEMO_FLYER =
  'data:image/svg+xml;utf8,' +
  encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="260"><rect width="200" height="260" fill="%23241748"/><text x="20" y="60" fill="%23D4AF37" font-family="Georgia" font-size="18">RESUME</text><text x="20" y="86" fill="%23D4AF37" font-family="Georgia" font-size="18">WORKSHOP</text></svg>'
  );

// Demo ownership is reviewer-only metadata. It is deliberately separate from
// the public contact fields on each event or opportunity.
const DEMO_SUBMITTER = {
  full_name: 'Deja Ware',
  org: 'C.O.D.E.',
};

// Simulated signed-in viewer shown when Supabase Auth isn't configured, so
// the submit form and admin review queue are walkable in demo mode too.
export const demoCurrentUser = {
  user: { email: 'demo@pvamu.edu' },
  role: {
    email: 'demo@pvamu.edu',
    role: 'super_admin',
    status: 'active',
    full_name: 'Demo Contributor',
    org: 'C.O.D.E.',
  },
};

export const samplePendingOpportunities = [
  {
    id: 'demo-pending-opp-1',
    title: 'Data Center Operations Intern — HP',
    org: 'CITE',
    type: 'Internship',
    paid: true,
    majors: ['Computer Science', 'Computer Engineering'],
    description: 'Hands-on internship supporting HP campus data center operations and network monitoring.',
    deadline: '2026-08-15',
    location: 'Houston, TX',
    link: 'https://example.com/apply',
    contact_name: 'Devon Reyes',
    contact_email: 'dreyes@pvamu.edu',
    flyer_url: DEMO_FLYER,
    status: 'pending',
    created_at: '2026-07-24',
    submitted_by: DEMO_SUBMITTER,
  },
];

export const samplePendingEvents = [
  {
    id: 'demo-pending-evt-1',
    title: 'IEEE Chapter Meeting',
    type: 'Org meeting',
    majors: ['Electrical Engineering', 'Computer Engineering'],
    description: 'Monthly IEEE chapter meeting — officer elections this month.',
    date: '2026-07-28',
    time: '6:00 PM',
    location: 'Engineering Bldg Rm 110',
    registration_link: null,
    contact_name: 'IEEE Chapter',
    contact_email: 'ieee@pvamu.edu',
    org: 'IEEE PVAMU',
    status: 'pending',
    created_at: '2026-07-24',
    submitted_by: DEMO_SUBMITTER,
  },
];

export const samplePendingAnnouncements = [
  {
    id: 'demo-pending-ann-1',
    source: 'Career Services',
    title: 'Fall Career Fair employer list posted',
    body: 'The full employer list for the fall career fair is now available on PawLink.',
    pinned: false,
    status: 'pending',
    created_at: '2026-07-25',
    submitted_by: DEMO_SUBMITTER,
  },
];

export const sampleOpportunities = [
  {
    id: 'demo-opp-peer-mentorship-2026',
    is_featured: true,
    spotlight_rank: 1,
    title: 'Engineering Peer-to-Peer Mentorship Program',
    org: 'College of Engineering Student Services',
    type: 'Other',
    paid: false,
    majors: ['All majors'],
    classifications: ['Sophomore', 'Junior', 'Senior'],
    work_mode: null,
    compensation_type: 'Not specified',
    description: 'A peer mentorship and leadership opportunity with monthly mixers, activities, professional-development opportunities, peer mentoring, and opportunities to connect freshmen with academics, campus resources, internships, research, and engineering organizations.',
    eligibility: 'Sophomore, junior, or senior Engineering or Computer Science student with a minimum 3.0 cumulative GPA.',
    deadline: '2026-09-11',
    location: null,
    link: 'https://forms.cloud.microsoft/r/zsURJTQZx3?origin=lprLink',
    source_url: 'https://forms.cloud.microsoft/r/zsURJTQZx3?origin=lprLink',
    source_name: 'Engineering Peer-to-Peer Mentorship Program application',
    contact_name: 'Jasmine Murry-Conner',
    contact_title: 'Program Coordinator II / CE²I Summer Bridge Director',
    contact_email: '',
    verified: true,
    submitted_by: DEMO_SUBMITTER,
    created_at: '2026-08-28',
  },
  {
    id: 'demo-opp-sc-capital-fellowship-2026',
    title: 'SC Capital Management Quantitative Research Fellowship',
    org: 'SC Capital Management',
    type: 'Research',
    paid: false,
    majors: ['Computer Science', 'All majors'],
    classifications: ['Junior', 'Senior', 'Graduate'],
    work_mode: 'Remote',
    compensation_type: 'Unpaid',
    description: 'Founding Cohort, Fall 2026–Spring 2027. Fellows commit 10–12 hours per week online and work with financial-market data analysis, research databases, trading-strategy evaluation, Python research tools, statistical modeling, and visualization. Two fellowship positions are available.',
    eligibility: 'Relevant areas include Computer Science, Data Science, Statistics, Applied Mathematics, Finance, Quantitative Economics, Business Analytics, and related quantitative disciplines. Juniors, seniors, and graduate students are preferred; exceptional sophomores may be considered.',
    deadline: '2026-08-31',
    location: 'Online',
    link: 'https://forms.gle/bh9SCLpgCsi6Hr9j8',
    source_url: 'https://forms.gle/bh9SCLpgCsi6Hr9j8',
    source_name: 'SC Capital Management fellowship application',
    contact_name: 'Dr. Kristena E. Cooksey',
    contact_title: 'Director, Quantitative Research Initiative',
    contact_email: '',
    verified: true,
    submitted_by: DEMO_SUBMITTER,
    created_at: '2026-08-28',
  },
  {
    id: 'demo-opp-hks-equitable-impact-2026',
    title: 'HKS Equitable Impact Fellowship',
    org: 'HKS',
    type: 'Other',
    paid: true,
    majors: ['All majors'],
    classifications: ['All classifications'],
    work_mode: 'In person',
    compensation_type: 'Paid',
    description: 'An eight-week paid summer fellowship at HKS U.S. offices combining client project work and research with a focus on architecture and professional design development.',
    eligibility: 'Current NOMA Student Member or Historically Black College or University student.',
    deadline: null,
    location: 'HKS U.S. Offices',
    link: null,
    contact_name: 'Cooper Evans',
    contact_email: 'ebcooper@pvamu.edu',
    contact_context: 'PVAMU forwarding contact/source',
    verified: true,
    submitted_by: DEMO_SUBMITTER,
    created_at: '2026-08-28',
  },
  {
    id: 'demo-opp-kamala-scholars-2026',
    title: '2026 Kamala Scholars Program',
    org: 'AnitaB.org',
    type: 'Scholarship',
    paid: false,
    majors: ['All majors'],
    classifications: ['Junior', 'Senior'],
    work_mode: null,
    compensation_type: 'Not specified',
    description: 'Scholarship and professional opportunity for eligible juniors and seniors. Additional award, requirement, benefit, and deadline details were not supplied for this demo entry.',
    eligibility: 'Juniors and seniors only.',
    deadline: null,
    location: null,
    link: 'https://ghc.anitab.org/kamala-scholars',
    source_url: 'https://ghc.anitab.org/kamala-scholars',
    source_name: 'Kamala Scholars Program',
    contact_name: '',
    contact_email: '',
    verified: true,
    submitted_by: DEMO_SUBMITTER,
    created_at: '2026-08-28',
  },
  {
    id: 'demo-opp-1',
    title: 'Software Engineering Co-op — Texas Instruments',
    org: 'Career Services',
    type: 'Co-op',
    paid: true,
    majors: ['Computer Science', 'Computer Engineering', 'Electrical Engineering'],
    classifications: ['Sophomore', 'Junior'],
    work_mode: 'In person',
    compensation_type: 'Paid',
    description:
      "Six-month rotational co-op on TI's embedded systems team in Dallas, TX.",
    eligibility: 'Open to sophomores and juniors in Computer Science, Computer Engineering, or Electrical Engineering.',
    deadline: '2026-08-14',
    location: 'Dallas, TX',
    link: 'https://example.com/apply',
    contact_name: 'Jasmine Miller',
    contact_email: 'jmiller@pvamu.edu',
    verified: true,
    flyer_url: DEMO_FLYER,
    created_at: '2026-07-10',
  },
  {
    id: 'demo-opp-2',
    title: 'SWE Regional Scholarship',
    org: 'Society of Women Engineers',
    type: 'Scholarship',
    paid: true,
    majors: ['All majors'],
    classifications: ['All classifications'],
    work_mode: 'Remote',
    compensation_type: 'Funded',
    description: 'Regional scholarship supporting engineering students.',
    eligibility: 'Open to all engineering majors in good academic standing.',
    deadline: '2026-08-02',
    location: 'N/A',
    link: 'https://example.com/apply',
    contact_name: 'SWE Chapter',
    contact_email: 'swe@pvamu.edu',
    verified: true,
    created_at: '2026-07-08',
  },
];

export const sampleEvents = [
  {
    id: 'demo-evt-disney-tech-info-2026',
    is_featured: true,
    spotlight_rank: 2,
    title: 'Disney Tech Internships Virtual Info Session',
    type: 'Other',
    category: 'Campus & University',
    majors: ['All majors'],
    description: 'PVAMU virtual session covering Disney Tech internships, including experiences from a PVAMU student and alumnus and discussion of the transition from internship to full-time Disney employment.',
    date: '2026-09-09',
    time: '5:00 PM–5:45 PM CST',
    location: 'Virtual',
    registration_link: 'https://events.teams.microsoft.com/event/661e7c3d-ab42-49e5-8b60-227f34ea56be@56b731a8-a2ac-4c32-bf6b-616810e913c6',
    source_url: 'https://events.teams.microsoft.com/event/661e7c3d-ab42-49e5-8b60-227f34ea56be@56b731a8-a2ac-4c32-bf6b-616810e913c6',
    source_name: 'Microsoft Teams registration',
    presenter_name: 'LaJoy C. Mercer',
    presenter_affiliation: 'Disney Campus Tech Recruitment / The Walt Disney Company',
    contact_name: 'LaJoy C. Mercer',
    contact_email: '',
    org: 'The Walt Disney Company / Disney on the Yard',
    verified: true,
    submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-panthers-invent-2026',
    title: "Panther's Invent 2026",
    type: 'Competition',
    categories: ['College of Engineering', 'Campus & University'],
    majors: ['All majors'],
    description: 'A 72-hour student innovation competition for students across disciplines. Theme: Resilient Peace: Strength Through Innovation. Presented by DRI/ICEED with Sandia National Laboratories as partner. Registration deadline shown on the supplied flyer: September 3, 2026.',
    date: '2026-09-11',
    end_date: '2026-09-13',
    time: '72-hour competition',
    location: 'Nathelyne Archie-Kennedy Building & Fabrication Center',
    registration_link: 'https://www.eventbrite.com/e/panthers-invent-2026-tickets-1998780178319?aff=oddtdtcreator',
    source_url: 'https://www.eventbrite.com/e/panthers-invent-2026-tickets-1998780178319?aff=oddtdtcreator',
    source_name: "Panther's Invent 2026 registration",
    contact_name: 'Darius Sims',
    contact_email: 'dgsims@pvamu.edu',
    org: 'DRI/ICEED',
    partner: 'Sandia National Laboratories',
    verified: true,
    submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-conocophillips-finance-it-networking-2026',
    title: 'College of Business: Finance & IT Pre-Career Fair Networking',
    type: 'Career fair',
    category: 'Campus & University',
    majors: ['Information Technology', 'Computer Science', 'Cybersecurity', 'Computer Engineering', 'Data Analytics', 'Related fields'],
    description: 'Meet the ConocoPhillips IT recruiting team to discuss internship and full-time opportunities. Students are encouraged to bring resumes, learn about careers at ConocoPhillips, and connect with recruiters and employees, including PVAMU alumni.',
    date: '2026-09-14',
    time: '6:00 PM–9:00 PM',
    location: 'Agriculture Business Building',
    contact_name: 'Jada Burks',
    contact_title: 'IT Business Analyst, Operations & Maintenance',
    contact_email: 'Jada.Burks@conocophillips.com',
    contact_phone: '281-293-2728',
    org: 'ConocoPhillips',
    source_name: 'Forwarded ConocoPhillips IT recruiting email',
    verified: true,
    submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-conocophillips-stem-town-2026',
    title: 'College of Engineering: STEM Town with ConocoPhillips',
    type: 'College event',
    category: 'College of Engineering',
    majors: ['Information Technology', 'Computer Science', 'Cybersecurity', 'Computer Engineering', 'Data Analytics', 'Related fields'],
    description: 'The ConocoPhillips IT recruiting team will connect with students and discuss internship and full-time opportunities. Students are encouraged to bring resumes and meet recruiters and employees, including PVAMU alumni.',
    date: '2026-09-14',
    time: '6:00 PM–9:00 PM',
    location: 'ENCARB Building Lobby',
    contact_name: 'Jada Burks',
    contact_title: 'IT Business Analyst, Operations & Maintenance',
    contact_email: 'Jada.Burks@conocophillips.com',
    contact_phone: '281-293-2728',
    org: 'ConocoPhillips',
    source_name: 'Forwarded ConocoPhillips IT recruiting email',
    verified: true,
    submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-conocophillips-pvamu-career-fair-2026',
    title: 'PVAMU Career Fair — ConocoPhillips IT Recruiting',
    type: 'Career fair',
    category: 'Campus & University',
    majors: ['Information Technology', 'Computer Science', 'Cybersecurity', 'Computer Engineering', 'Data Analytics', 'Related fields'],
    description: 'Visit the ConocoPhillips booth to discuss internship and full-time opportunities with IT recruiters and employees, including PVAMU alumni. Students are encouraged to bring resumes.',
    date: '2026-09-15',
    end_date: '2026-09-16',
    time: '10:00 AM–3:00 PM',
    location: 'Student Recreation Center',
    contact_name: 'Jada Burks',
    contact_title: 'IT Business Analyst, Operations & Maintenance',
    contact_email: 'Jada.Burks@conocophillips.com',
    contact_phone: '281-293-2728',
    org: 'ConocoPhillips',
    source_name: 'Forwarded ConocoPhillips IT recruiting email',
    verified: true,
    submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-meet-dean-2026',
    title: 'Meet the Dean Mix & Mingle',
    type: 'College event',
    category: 'College of Engineering',
    majors: ['All majors'],
    description: 'Meet the Dean Mix & Mingle.',
    date: '2026-09-17',
    time: '12:00 PM–2:00 PM',
    location: 'ENCARB Foyer',
    contact_name: '', contact_email: '', org: 'College of Engineering Student Services', verified: true, submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-coe-voting-2026', title: 'Mr. & Miss College of Engineering Voting', type: 'College event', category: 'College of Engineering', majors: ['All majors'],
    description: 'Mr. & Miss College of Engineering voting. Time and location were not provided.', date: '2026-09-17', time: 'Time not provided', location: 'Location not provided',
    contact_name: '', contact_email: '', org: 'College of Engineering Student Services', verified: true, submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-peer-speed-matching-2026', title: 'Peer-to-Peer Mentorship Speed Matching', type: 'College event', category: 'College of Engineering', majors: ['All majors'],
    description: 'Peer-to-Peer Mentorship Speed Matching.', date: '2026-10-01', time: '12:00 PM–1:30 PM', location: 'ENCARB',
    contact_name: '', contact_email: '', org: 'College of Engineering Student Services', verified: true, submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-homecoming-mixer-2026', title: 'Homecoming Faculty, Staff, Students & Alumni Mixer', type: 'College event', category: 'College of Engineering', majors: ['All majors'],
    description: 'A Homecoming gathering featuring Panther pride, food, music, games, and fellowship.', date: '2026-10-17', time: '11:00 AM–2:00 PM', location: 'ENCARB Patio',
    contact_name: '', contact_email: '', org: 'College of Engineering Student Services', verified: true, submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-shpe-conference-2026', title: 'SHPE Conference', type: 'Other', category: 'Engineering Student Organizations', majors: ['All majors'],
    description: 'SHPE Conference.', date: '2026-10-28', end_date: '2026-10-31', time: 'Time not provided', location: 'Indianapolis, IN',
    contact_name: '', contact_email: '', org: 'SHPE', verified: true, submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-swe-conference-2026', title: 'SWE Conference', type: 'Other', category: 'Engineering Student Organizations', majors: ['All majors'],
    description: 'SWE Conference.', date: '2026-11-05', end_date: '2026-11-07', time: 'Time not provided', location: 'Boston, MA',
    contact_name: '', contact_email: '', org: 'SWE', verified: true, submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-nsbe-regional-2026', title: 'NSBE Regional Conference', type: 'Other', category: 'Engineering Student Organizations', majors: ['All majors'],
    description: 'NSBE Regional Conference.', date: '2026-11-12', end_date: '2026-11-15', time: 'Time not provided', location: 'Tulsa',
    contact_name: '', contact_email: '', org: 'NSBE', verified: true, submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-peer-mentorship-mixer-2026', title: 'Peer-to-Peer Mentorship Mixer', type: 'College event', category: 'College of Engineering', majors: ['All majors'],
    description: 'Peer-to-Peer Mentorship Mixer. Additional details are TBA.', date: '2026-11-17', time: 'TBA', location: 'TBA',
    contact_name: '', contact_email: '', org: 'College of Engineering Student Services', verified: true, submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-thanksgiving-bingo-2026', title: 'Engineering Thanksgiving Bingo', type: 'College event', category: 'College of Engineering', majors: ['All majors'],
    description: 'Engineering Thanksgiving Bingo.', date: '2026-11-19', time: '12:00 PM–2:00 PM', location: 'ENCARB Foyer',
    contact_name: '', contact_email: '', org: 'College of Engineering Student Services', verified: true, submitted_by: DEMO_SUBMITTER,
  },
  {
    id: 'demo-evt-jingle-mingle-2026', title: 'Jingle & Mingle Holiday Gathering', type: 'College event', category: 'College of Engineering', majors: ['All majors'],
    description: 'Holiday gathering for faculty and staff.', date: '2026-12-09', time: '12:00 PM–1:30 PM', location: 'ENCARB', audience: 'Faculty & Staff',
    contact_name: '', contact_email: '', org: 'College of Engineering Student Services', verified: true, submitted_by: DEMO_SUBMITTER,
  },
  ...['2026-09-01', '2026-09-08', '2026-09-15', '2026-09-22', '2026-09-29'].map((date) => ({
    id: `demo-evt-noonday-meditation-${date}`,
    title: 'Tuesday Noonday Meditation',
    type: 'Other',
    category: 'Campus & University',
    majors: ['All majors'],
    description: 'Tuesday Noonday Meditation.',
    date,
    time: '12:00 PM–12:30 PM',
    location: 'Johnson-Phillip All Faiths Chapel',
    contact_name: 'Mary Daniels',
    contact_email: 'mjdaniels@pvamu.edu',
    org: 'Prairie View A&M University',
    verified: true,
    submitted_by: DEMO_SUBMITTER,
  })),
  // TODO: Revisit after official verification. Do not publish the tentative
  // Sept. 23 Engineering Student Organization Involvement Fair or Nov. 16
  // VROOM Car Show & Professionalism Event. Spring 2027 events are excluded.
  {
    id: 'demo-evt-1',
    title: 'Resume Workshop',
    type: 'Workshop',
    majors: ['All majors'],
    description:
      "A hands-on session with Career Services to build or refine your resume ahead of the fall career fair.",
    date: '2026-07-29',
    time: '4:00 PM – 5:15 PM',
    location: 'CITE Lab, Engineering Bldg 2nd Floor',
    registration_link: null,
    presenter_name: 'Devon Reyes',
    presenter_affiliation: 'PVAMU Alum · Texas Instruments',
    contact_name: 'Jasmine Miller',
    contact_email: 'jmiller@pvamu.edu',
    verified: true,
    flyer_url: DEMO_FLYER,
  },
  {
    id: 'demo-evt-2',
    title: 'Employer Info Session: ExxonMobil',
    type: 'Career fair',
    majors: ['All majors'],
    description: 'Meet ExxonMobil recruiters and learn about internship and full-time openings.',
    date: '2026-07-31',
    time: '5:30 PM',
    location: 'Engineering Bldg Rm 204',
    registration_link: null,
    presenter_name: null,
    presenter_affiliation: null,
    contact_name: 'Career Services',
    contact_email: 'careers@pvamu.edu',
    verified: true,
  },
];

export const sampleAnnouncements = [
  {
    id: 'demo-ann-1',
    source: 'College of Engineering',
    title: 'Fall move-in engineering orientation schedule is posted',
    body: 'All incoming engineering students should review the updated orientation week schedule.',
    category: 'Academic', source_url: 'https://www.pvamu.edu/engineering/', published_at: '2026-09-04T14:00:00Z',
    pinned: true,
    priority: 'leadership', is_featured: true, featured_until: '2026-12-31', expires_at: null,
    created_at: '2026-07-23',
  },
  {
    id: 'demo-ann-2',
    source: 'C.O.D.E.',
    title: 'The Engineering Hub pilot is live',
    body: 'Org presidents can now request calendar access — reach out to your C.O.D.E. rep.',
    category: 'C.O.D.E.', source_url: null, published_at: '2026-09-02T15:00:00Z',
    pinned: false,
    priority: 'code', is_featured: true, featured_until: '2026-12-31', expires_at: null,
    created_at: '2026-07-22',
  },
  { id: 'demo-ann-3', source: 'Roy G. Perry College of Engineering', title: 'Engineering student resource center hours updated', body: 'The student resource center has published its fall hours for advising, tutoring, and student support.', category: 'College', source_url: 'https://www.pvamu.edu/engineering/', pinned: false, priority: 'leadership', is_featured: false, featured_until: null, expires_at: null, published_at: '2026-08-29T14:00:00Z', created_at: '2026-08-29' },
  { id: 'demo-ann-4', source: 'Office of Academic Programs', title: 'Important fall registration dates and deadlines', body: 'Review the remaining registration milestones and academic deadlines for the fall semester.', category: 'Academic', source_url: null, pinned: false, priority: 'standard', is_featured: false, featured_until: null, expires_at: null, published_at: '2026-08-26T14:00:00Z', created_at: '2026-08-26' },
  { id: 'demo-ann-5', source: 'Electrical and Computer Engineering', title: 'Department advising schedule now available', body: 'Students may reserve fall advising appointments through the department advising office.', category: 'Department', source_url: null, pinned: false, priority: 'standard', is_featured: false, featured_until: null, expires_at: null, published_at: '2026-08-23T14:00:00Z', created_at: '2026-08-23' },
  { id: 'demo-ann-6', source: 'National Society of Black Engineers', title: 'Student chapter interest meeting announced', body: 'Meet chapter leaders, learn about upcoming programs, and find ways to participate this semester.', category: 'Student Organization', source_url: null, pinned: false, priority: 'campus', is_featured: false, featured_until: null, expires_at: null, published_at: '2026-08-20T14:00:00Z', created_at: '2026-08-20' },
  { id: 'demo-ann-7', source: 'C.O.D.E.', title: 'Engineering student ambassadors applications open', body: 'Represent the engineering community and help connect students with programs, resources, and support.', category: 'C.O.D.E.', source_url: null, pinned: false, priority: 'code', is_featured: false, featured_until: null, expires_at: null, published_at: '2026-08-18T14:00:00Z', created_at: '2026-08-18' },
  { id: 'demo-ann-8', source: 'Roy G. Perry College of Engineering', title: 'Engineering building access reminder', body: 'Please review current building access procedures before your next evening or weekend visit.', category: 'General', source_url: 'https://www.pvamu.edu/engineering/', pinned: false, priority: 'standard', is_featured: false, featured_until: null, expires_at: null, published_at: '2026-08-15T14:00:00Z', created_at: '2026-08-15' },
];

// Deterministic aggregate demo analytics. These are labeled as sample values
// in the UI and never imply unique students or completed applications.
export const sampleOpportunityConnections = 84;

export const sampleEngagementMetrics = Object.freeze({
  week: { available: true, counts: {
    opportunity: { detail_view: 126, application_click: 31, source_click: 18, calendar_outlook: 9, calendar_google: 14 },
    event: { detail_view: 164, registration_click: 42, source_click: 21, calendar_outlook: 27, calendar_google: 35 },
    announcement: { list_view: 73 },
  } },
  month: { available: true, counts: {
    opportunity: { detail_view: 418, application_click: 84, source_click: 51, calendar_outlook: 28, calendar_google: 44 },
    event: { detail_view: 506, registration_click: 119, source_click: 63, calendar_outlook: 82, calendar_google: 106 },
    announcement: { list_view: 241 },
  } },
  all: { available: true, counts: {
    opportunity: { detail_view: 418, application_click: 84, source_click: 51, calendar_outlook: 28, calendar_google: 44 },
    event: { detail_view: 506, registration_click: 119, source_click: 63, calendar_outlook: 82, calendar_google: 106 },
    announcement: { list_view: 241 },
  } },
});
