'use client';
import { useState, useTransition } from 'react';
import { approveItem, rejectItem, requestCorrection } from '../../actions';
const emptyEvidence={official_source_opened:false,primary_link_checked:false,essential_facts_verified:false,contact_organization_verified:false,safe_content_confirmed:false};
export default function ReviewSubmission({item,type}){
 const [evidence,setEvidence]=useState(emptyEvidence),[note,setNote]=useState(''),[message,setMessage]=useState(''); const [busy,startTransition]=useTransition(); const complete=Object.values(evidence).every(Boolean);
 function decide(action){if(action==='approve'&&!complete){setMessage('Complete all required verification items before publishing.');return;}if((action==='reject'||action==='correction')&&!note.trim()){setMessage('Add reviewer notes before requesting correction or rejecting.');return;}setMessage('Saving review decision…');startTransition(async()=>{const result=action==='approve'?await approveItem(type,item.id,{...evidence,reviewer_notes:note}):action==='reject'?await rejectItem(type,item.id,note,evidence):await requestCorrection(type,item.id,note);setMessage(result.ok?(action==='approve'?'Approved and published.':action==='reject'?'Rejected and audited.':'Correction request recorded and audited.'):(result.error||'Action failed.'));});}
 return <div className="review-submission-layout"><section className="review-submission-source"><div className="eyebrow">Submitted content</div><h2>{item.title}</h2><dl><dt>Organization</dt><dd>{item.org||item.source||'Not provided'}</dd><dt>Submitted by</dt><dd>{item.submitted_by?.full_name||item.submitted_by?.email||'CODE intake'}</dd>{item.description&&<><dt>Description</dt><dd>{item.description}</dd></>}{item.body&&<><dt>Body</dt><dd>{item.body}</dd></>}{item.date&&<><dt>Event date</dt><dd>{item.date} {item.time||''}</dd></>}{item.deadline&&<><dt>Deadline</dt><dd>{item.deadline}</dd></>}{item.location&&<><dt>Location</dt><dd>{item.location}</dd></>}{item.eligibility&&<><dt>Eligibility</dt><dd>{item.eligibility}</dd></>}{item.contact_name&&<><dt>PVAMU contact</dt><dd>{item.contact_name}{item.contact_email?` · ${item.contact_email}`:''}</dd></>}</dl>{item.source_url&&<a className="gold-button" href={item.source_url} target="_blank" rel="noreferrer">Open official source ↗</a>}</section><section className="review-submission-controls"><div className="eyebrow">Verification checklist</div><h2>Confirm before publishing</h2>{[['official_source_opened','Official source opened'],['primary_link_checked','Primary application or registration link checked'],['essential_facts_verified','Essential title, date, deadline, location, and eligibility facts verified'],['contact_organization_verified','Contact, organization, and submitted-by distinction verified'],['safe_content_confirmed','Content and links are safe and appropriate']].map(([key,label])=><label key={key}><input type="checkbox" checked={evidence[key]} onChange={event=>setEvidence(current=>({...current,[key]:event.target.checked}))}/> {label}</label>)}<label className="review-note-label">Reviewer notes<textarea rows="5" value={note} onChange={event=>setNote(event.target.value)} placeholder="Required for corrections or rejection."/></label><p className="workspace-status" role="status" aria-live="polite">{message}</p><div className="review-submission-actions"><button className="chip" disabled={busy} onClick={()=>decide('correction')}>Needs Correction</button><button className="chip" disabled={busy} onClick={()=>decide('reject')}>Reject</button><button className="gold-button" disabled={busy||!complete} onClick={()=>decide('approve')}>Approve &amp; Publish</button></div></section></div>;
}
